import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { CalendarDays, CreditCard, MoreHorizontal, Pencil, Plus, ReceiptText, Trash2, Users } from 'lucide-react';
import Card from '../components/ui/Card';
import Modal from '../components/ui/Modal';
import ConfirmModal from '../components/ui/ConfirmModal';
import Toast from '../components/ui/Toast';
import ProgressBar from '../components/ui/ProgressBar';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import { formatDisplayDate, getLocalDateString } from '../utils/dateUtils';

const currency = (value) => `R$ ${(Number(value) || 0).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const inputClass = 'mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10 disabled:opacity-50 dark:border-slate-700 dark:bg-slate-800 dark:text-white';
const monthNames = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'];

const InvestmentsRedesigned = () => {
    const { viewMode } = useOutletContext() || {}; const { user, partner } = useAuth();
    const [cards, setCards] = useState([]); const [invoices, setInvoices] = useState([]); const [wallets, setWallets] = useState([]); const [loading, setLoading] = useState(true); const [toast, setToast] = useState(null); const [cardModal, setCardModal] = useState(false); const [invoiceModal, setInvoiceModal] = useState(false); const [editingCard, setEditingCard] = useState(null); const [editingInvoice, setEditingInvoice] = useState(null); const [deletingCard, setDeletingCard] = useState(null); const [deletingInvoice, setDeletingInvoice] = useState(null);
    const blankCard = { name: '', limit: '', due_day: '10', closing_day: '5', is_joint: true, current_used_limit: '' }; const blankInvoice = { credit_card_id: '', month: new Date().getMonth() + 1, year: new Date().getFullYear(), amount: '', due_date: getLocalDateString(), paid: false, wallet_id: '' };
    const [cardForm, setCardForm] = useState(blankCard); const [invoiceForm, setInvoiceForm] = useState(blankInvoice);
    const loadCards = useCallback(async () => { setLoading(true); try { const [{ data: cardData }, { data: walletData }] = await Promise.all([api.get('/credit-cards', { params: { viewMode: viewMode || 'joint' } }), api.get('/wallets')]); setCards(cardData); setWallets(walletData); } catch (error) { console.error(error); } finally { setLoading(false); } }, [viewMode]);
    const loadInvoices = useCallback(async () => { try { const { data } = await api.get('/invoices', { params: { viewMode: viewMode || 'joint' } }); setInvoices(data); } catch (error) { console.error(error); } }, [viewMode]);
    useEffect(() => { loadCards(); }, [loadCards]); useEffect(() => { if (cards.length) loadInvoices(); else setInvoices([]); }, [cards, loadInvoices]);
    const currentMonth = new Date().getMonth() + 1; const currentYear = new Date().getFullYear();
    const cardInfo = useCallback((card) => { const invoice = invoices.find((item) => item.credit_card_id === card.id && item.month === currentMonth && item.year === currentYear && !item.paid); const debt = Number(card.monthly_amount || invoice?.amount || 0); const limit = Number(card.limit || 0); return { debt, limit, available: Math.max(0, limit - debt), percentage: limit ? Math.min(100, debt / limit * 100) : 0 }; }, [invoices, currentMonth, currentYear]);
    const totals = useMemo(() => cards.reduce((result, card) => { const info = cardInfo(card); return { limit: result.limit + info.limit, debt: result.debt + info.debt }; }, { limit: 0, debt: 0 }), [cards, cardInfo]);
    const openCard = (card = null) => { setEditingCard(card); setCardForm(card ? { name: card.name, limit: String(card.limit), due_day: String(card.due_day), closing_day: String(card.closing_day), is_joint: card.is_joint !== false, current_used_limit: String(card.current_debt || '') } : blankCard); setCardModal(true); };
    const saveCard = async (event) => { event.preventDefault(); try { const payload = { name: cardForm.name, limit: Number(cardForm.limit), due_day: Number(cardForm.due_day), closing_day: Number(cardForm.closing_day), is_joint: cardForm.is_joint, current_debt: Number(cardForm.current_used_limit) || 0 }; if (editingCard) await api.put(`/credit-cards/${editingCard.id}`, payload); else await api.post('/credit-cards', payload); setCardModal(false); await loadCards(); setToast({ message: editingCard ? 'Cartão atualizado.' : 'Cartão adicionado.', type: 'success' }); } catch (error) { setToast({ message: error.response?.data?.error || 'Erro ao salvar cartão.', type: 'error' }); } };
    const openInvoice = (card = null, invoice = null) => { setEditingInvoice(invoice); setInvoiceForm(invoice ? { credit_card_id: invoice.credit_card_id, month: invoice.month, year: invoice.year, amount: invoice.amount, due_date: invoice.due_date.split('T')[0], paid: invoice.paid, wallet_id: '' } : { ...blankInvoice, credit_card_id: card?.id || '' }); setInvoiceModal(true); };
    const saveInvoice = async (event) => { event.preventDefault(); if (invoiceForm.paid && !invoiceForm.wallet_id) { setToast({ message: 'Selecione a carteira usada no pagamento.', type: 'error' }); return; } try { await api.post('/invoices', invoiceForm); setInvoiceModal(false); await loadInvoices(); setToast({ message: editingInvoice ? 'Fatura atualizada.' : 'Fatura registrada.', type: 'success' }); } catch (error) { setToast({ message: error.response?.data?.error || 'Erro ao salvar fatura.', type: 'error' }); } };
    const removeCard = async () => { try { await api.delete(`/credit-cards/${deletingCard}`); setDeletingCard(null); await loadCards(); setToast({ message: 'Cartão excluído.', type: 'success' }); } catch (error) { setToast({ message: error.response?.data?.error || 'Erro ao excluir cartão.', type: 'error' }); } };
    const removeInvoice = async () => { try { await api.delete(`/invoices/${deletingInvoice}`); setDeletingInvoice(null); await loadInvoices(); setToast({ message: 'Fatura excluída.', type: 'success' }); } catch (error) { setToast({ message: error.response?.data?.error || 'Erro ao excluir fatura.', type: 'error' }); } };
    if (loading) return <div className="flex h-64 items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-b-2 border-emerald-500" /></div>;
    return <div className="space-y-6 pb-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-sm font-semibold text-emerald-600">Crédito com clareza</p><h1 className="text-2xl font-semibold tracking-tight text-slate-950 dark:text-white">Cartões de crédito</h1><p className="mt-1 text-sm text-slate-500">Acompanhem cartões pessoais e conjuntos, limites e faturas.</p></div><button onClick={() => openCard()} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-emerald-500 px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-600"><Plus size={17} /> Adicionar cartão</button></header>
        <div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><Summary label="Limite total" value={currency(totals.limit)} icon={<CreditCard size={17} />} /><Summary label="Utilizado neste mês" value={currency(totals.debt)} icon={<ReceiptText size={17} />} tone="rose" /><Summary label="Disponível" value={currency(Math.max(0, totals.limit - totals.debt))} icon={<Users size={17} />} tone="emerald" /></div>
        {cards.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cards.map((card) => { const info = cardInfo(card); return <Card key={card.id} className="group relative overflow-hidden p-5"><div className="absolute right-0 top-0 h-32 w-32 translate-x-10 -translate-y-10 rounded-full bg-emerald-400/10 blur-2xl" /><div className="relative flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-950 text-white dark:bg-emerald-500"><CreditCard size={20} /></div><div className="flex gap-1 opacity-0 transition group-hover:opacity-100"><button onClick={() => openInvoice(card)} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100 hover:text-emerald-600 dark:hover:bg-slate-800" title="Adicionar fatura"><Plus size={15} /></button><button onClick={() => openCard(card)} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100 hover:text-blue-600 dark:hover:bg-slate-800"><Pencil size={15} /></button><button onClick={() => setDeletingCard(card.id)} className="rounded-xl p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-slate-800"><Trash2 size={15} /></button></div></div><div className="relative mt-6"><div className="flex items-center justify-between gap-2"><h2 className="truncate font-semibold text-slate-950 dark:text-white">{card.name}</h2><span className="shrink-0 rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-semibold text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-400">{card.is_joint === false ? `Pessoal · ${card.User?.name || user?.name || 'Você'}` : 'Conjunto'}</span></div><p className="mt-1 text-xs text-slate-500">Fecha dia {card.closing_day} · vence dia {card.due_day}</p><div className="mt-6 flex items-end justify-between"><div><p className="text-xs text-slate-500">Usado</p><p className="mt-1 text-xl font-semibold">{currency(info.debt)}</p></div><div className="text-right"><p className="text-xs text-slate-500">Disponível</p><p className="mt-1 text-sm font-semibold text-emerald-600">{currency(info.available)}</p></div></div><div className="mt-4"><ProgressBar progress={info.percentage} colorClass={info.percentage > 80 ? 'bg-rose-500' : 'bg-emerald-500'} height="h-2" /><p className="mt-2 text-right text-xs text-slate-400">{info.percentage.toFixed(0)}% do limite</p></div></div></Card>; })}</div> : <Card className="py-16 text-center"><CreditCard className="mx-auto mb-3 text-slate-300" size={36} /><h2 className="font-semibold text-slate-900 dark:text-white">Nenhum cartão cadastrado</h2><p className="mt-1 text-sm text-slate-500">Adicione o primeiro cartão para acompanhar as faturas.</p></Card>}
        <Card className="overflow-hidden p-0"><div className="flex items-center justify-between border-b border-slate-100 p-5 dark:border-slate-800"><div><h2 className="font-semibold text-slate-950 dark:text-white">Faturas</h2><p className="mt-1 text-xs text-slate-500">Histórico das faturas registradas</p></div><CalendarDays size={18} className="text-slate-400" /></div>{invoices.length ? <div className="divide-y divide-slate-100 dark:divide-slate-800">{invoices.map((invoice) => { const card = cards.find((item) => item.id === invoice.credit_card_id); return <div key={invoice.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-slate-100 p-2.5 text-slate-600 dark:bg-slate-800 dark:text-slate-300"><ReceiptText size={17} /></div><div><p className="font-medium text-slate-900 dark:text-white">{card?.name || 'Cartão'} · {monthNames[invoice.month - 1]}/{invoice.year}</p><p className="mt-1 text-xs text-slate-500">Vencimento {formatDisplayDate(invoice.due_date)}</p></div></div><div className="flex items-center justify-between gap-4 sm:justify-end"><div className="text-left sm:text-right"><p className="font-semibold">{currency(invoice.amount)}</p><span className={`text-xs font-medium ${invoice.paid ? 'text-emerald-600' : 'text-amber-600'}`}>{invoice.paid ? 'Paga' : 'Pendente'}</span></div><button onClick={() => openInvoice(null, invoice)} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100 hover:text-blue-600 dark:hover:bg-slate-800"><Pencil size={15} /></button><button onClick={() => setDeletingInvoice(invoice.id)} className="rounded-xl p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-slate-800"><Trash2 size={15} /></button></div></div>; })}</div> : <div className="p-12 text-center text-sm text-slate-400">Nenhuma fatura registrada. Use o botão + em um cartão para adicionar.</div>}</Card>
        <Modal isOpen={cardModal} onClose={() => setCardModal(false)} title={editingCard ? 'Editar cartão' : 'Novo cartão'}><form onSubmit={saveCard} className="space-y-4"><div><span className="text-sm font-medium">Tipo de cartão</span><p className="mt-1 text-xs text-slate-500">Escolha se o limite pertence aos dois ou somente a você.</p><div className="mt-2 grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-1 dark:bg-slate-800"><button type="button" onClick={() => setCardForm({ ...cardForm, is_joint: true })} className={`rounded-xl py-2 text-sm font-medium ${cardForm.is_joint ? 'bg-white text-emerald-600 shadow-sm dark:bg-slate-700' : 'text-slate-500'}`}>Conjunto</button><button type="button" onClick={() => setCardForm({ ...cardForm, is_joint: false })} className={`rounded-xl py-2 text-sm font-medium ${!cardForm.is_joint ? 'bg-white text-emerald-600 shadow-sm dark:bg-slate-700' : 'text-slate-500'}`}>Pessoal</button></div></div><label className="block text-sm font-medium">Nome do cartão<input required className={inputClass} value={cardForm.name} onChange={(event) => setCardForm({ ...cardForm, name: event.target.value })} placeholder="Ex.: Nubank Platinum" /></label><div className="grid grid-cols-2 gap-3"><label className="block text-sm font-medium">Limite<input required type="number" step="0.01" className={inputClass} value={cardForm.limit} onChange={(event) => setCardForm({ ...cardForm, limit: event.target.value })} /></label><label className="block text-sm font-medium">Já utilizado<input type="number" step="0.01" className={inputClass} value={cardForm.current_used_limit} onChange={(event) => setCardForm({ ...cardForm, current_used_limit: event.target.value })} /></label><label className="block text-sm font-medium">Fecha dia<input required type="number" min="1" max="31" className={inputClass} value={cardForm.closing_day} onChange={(event) => setCardForm({ ...cardForm, closing_day: event.target.value })} /></label><label className="block text-sm font-medium">Vence dia<input required type="number" min="1" max="31" className={inputClass} value={cardForm.due_day} onChange={(event) => setCardForm({ ...cardForm, due_day: event.target.value })} /></label></div><button className="w-full rounded-2xl bg-emerald-500 py-3 font-semibold text-white hover:bg-emerald-600">Salvar cartão</button></form></Modal>
        <Modal isOpen={invoiceModal} onClose={() => setInvoiceModal(false)} title={editingInvoice ? 'Editar fatura' : 'Nova fatura'}><form onSubmit={saveInvoice} className="space-y-4"><label className="block text-sm font-medium">Cartão<select required disabled={!!editingInvoice} className={inputClass} value={invoiceForm.credit_card_id} onChange={(event) => setInvoiceForm({ ...invoiceForm, credit_card_id: event.target.value })}><option value="">Selecione</option>{cards.map((card) => <option key={card.id} value={card.id}>{card.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="block text-sm font-medium">Mês<select disabled={!!editingInvoice} className={inputClass} value={invoiceForm.month} onChange={(event) => setInvoiceForm({ ...invoiceForm, month: Number(event.target.value) })}>{monthNames.map((month, index) => <option key={month} value={index + 1}>{month}</option>)}</select></label><label className="block text-sm font-medium">Ano<input disabled={!!editingInvoice} type="number" className={inputClass} value={invoiceForm.year} onChange={(event) => setInvoiceForm({ ...invoiceForm, year: Number(event.target.value) })} /></label></div><label className="block text-sm font-medium">Valor<input required type="number" step="0.01" className={inputClass} value={invoiceForm.amount} onChange={(event) => setInvoiceForm({ ...invoiceForm, amount: event.target.value })} placeholder="0,00" /></label><label className="block text-sm font-medium">Vencimento<input required type="date" className={inputClass} value={invoiceForm.due_date} onChange={(event) => setInvoiceForm({ ...invoiceForm, due_date: event.target.value })} /></label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={invoiceForm.paid} onChange={(event) => setInvoiceForm({ ...invoiceForm, paid: event.target.checked })} /> Fatura já foi paga</label>{invoiceForm.paid && <label className="block text-sm font-medium">Carteira usada no pagamento<select required className={inputClass} value={invoiceForm.wallet_id} onChange={(event) => setInvoiceForm({ ...invoiceForm, wallet_id: event.target.value })}><option value="">Selecione</option>{wallets.map((wallet) => <option key={wallet.id} value={wallet.id}>{wallet.name}</option>)}</select></label>}<button className="w-full rounded-2xl bg-emerald-500 py-3 font-semibold text-white hover:bg-emerald-600">Salvar fatura</button></form></Modal>
        <ConfirmModal isOpen={!!deletingCard} onClose={() => setDeletingCard(null)} onConfirm={removeCard} title="Excluir cartão" message="Tem certeza que deseja excluir este cartão?" type="danger" confirmText="Excluir" cancelText="Cancelar" /><ConfirmModal isOpen={!!deletingInvoice} onClose={() => setDeletingInvoice(null)} onConfirm={removeInvoice} title="Excluir fatura" message="Tem certeza que deseja excluir esta fatura?" type="danger" confirmText="Excluir" cancelText="Cancelar" />{toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}</div>;
};
const Summary = ({ label, value, icon, tone = 'blue' }) => <Card className="p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-medium text-slate-500">{label}</span><span className={`rounded-xl p-2 ${tone === 'rose' ? 'bg-rose-50 text-rose-500' : tone === 'emerald' ? 'bg-emerald-50 text-emerald-600' : 'bg-blue-50 text-blue-600'}`}>{icon}</span></div><p className="truncate text-lg font-semibold text-slate-950 dark:text-white">{value}</p></Card>;
export default InvestmentsRedesigned;
