import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowRightLeft, BarChart3, Building2, CalendarDays, Calculator, ChevronRight, CreditCard, LineChart, LogOut, Settings, Target, Trophy, Users, Wallet, Zap } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

const groups = [
    { title: 'Finanças', items: [{ title: 'Transações', description: 'Histórico e lançamentos', icon: ArrowRightLeft, color: 'text-emerald-600', path: '/dashboard/transactions' }, { title: 'Carteiras', description: 'Contas e saldos', icon: Wallet, color: 'text-blue-600', path: '/dashboard/wallets' }, { title: 'Cartões', description: 'Limites e faturas', icon: CreditCard, color: 'text-amber-600', path: '/dashboard/investments' }, { title: 'Banco', description: 'Contas conectadas', icon: Building2, color: 'text-violet-600', path: '/dashboard/bank' }] },
    { title: 'Planejamento', items: [{ title: 'Objetivos', description: 'Metas do casal', icon: Target, color: 'text-rose-600', path: '/dashboard/goals' }, { title: 'Simulador', description: 'Planeje compras e sonhos', icon: Calculator, color: 'text-indigo-600', path: '/dashboard/simulation' }, { title: 'Previsão', description: 'Projete seu patrimônio', icon: BarChart3, color: 'text-teal-600', path: '/dashboard/economy-forecast' }, { title: 'Recorrências', description: 'Contas fixas do mês', icon: CalendarDays, color: 'text-orange-600', path: '/dashboard/recurring' }] },
    { title: 'Evolução', items: [{ title: 'Estatísticas', description: 'Gráficos e hábitos', icon: LineChart, color: 'text-cyan-600', path: '/dashboard/forecast' }, { title: 'Desafios', description: 'Hábitos financeiros', icon: Zap, color: 'text-yellow-600', path: '/dashboard/challenges' }, { title: 'Conquistas', description: 'Pontos e medalhas', icon: Trophy, color: 'text-purple-600', path: '/dashboard/achievements' }] }
];

const MobileMenuRedesigned = () => {
    const navigate = useNavigate(); const location = useLocation(); const { user, partner, logout } = useAuth();
    return <div className="space-y-7 pb-8">
        <header className="rounded-[24px] border border-emerald-100 bg-emerald-50 p-5 text-slate-900 dark:border-emerald-900/40 dark:bg-emerald-950/30 dark:text-white"><div className="flex items-center justify-between"><div><p className="text-xs font-medium text-emerald-700 dark:text-emerald-300">Seu espaço Duoo</p><h1 className="mt-1 text-2xl font-semibold">Menu</h1></div><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-500 text-white"><Users size={20} /></div></div><p className="mt-5 text-sm text-slate-700 dark:text-slate-200">{partner ? `${user?.name?.split(' ')[0] || 'Você'} & ${partner.name?.split(' ')[0] || 'parceiro'}` : user?.name || 'Sua conta'}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Acessem tudo que importa para a vida financeira.</p></header>
        {groups.map((group) => <section key={group.title} className="space-y-3"><h2 className="px-1 text-sm font-semibold text-slate-500">{group.title}</h2><div className="grid grid-cols-2 gap-3">{group.items.map((item) => <MenuTile key={item.path} item={item} active={location.pathname === item.path} onClick={() => navigate(item.path)} />)}</div></section>)}
        <div className="space-y-3"><ActionButton icon={<Users size={18} />} title="Conta do casal" description="Gerenciar vínculo e convite" onClick={() => navigate('/dashboard/link-accounts')} /><ActionButton icon={<Settings size={18} />} title="Configurações" description="Preferências e segurança" onClick={() => navigate('/dashboard/settings')} /><button onClick={logout} className="flex w-full items-center gap-3 rounded-2xl border border-rose-100 bg-rose-50 p-4 text-left text-rose-600 dark:border-rose-900/30 dark:bg-rose-950/20"><LogOut size={18} /><span className="text-sm font-semibold">Sair da conta</span></button></div>
    </div>;
};

const MenuTile = ({ item, active, onClick }) => { const Icon = item.icon; return <button onClick={onClick} className={`rounded-[20px] border p-4 text-left transition active:scale-[.98] ${active ? 'border-emerald-300 bg-emerald-50/60 dark:border-emerald-800 dark:bg-emerald-950/20' : 'border-slate-200 bg-white hover:border-slate-300 dark:border-slate-800 dark:bg-slate-900'}`}><span className={`mb-4 flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-100 ${item.color} dark:bg-slate-800`}><Icon size={19} /></span><span className="block text-sm font-semibold text-slate-900 dark:text-white">{item.title}</span><span className="mt-1 block text-[11px] leading-relaxed text-slate-500">{item.description}</span></button>; };
const ActionButton = ({ icon, title, description, onClick }) => <button onClick={onClick} className="flex w-full items-center justify-between rounded-2xl border border-slate-200 bg-white p-4 text-left dark:border-slate-800 dark:bg-slate-900"><span className="flex items-center gap-3"><span className="rounded-xl bg-slate-100 p-2 text-slate-500 dark:bg-slate-800">{icon}</span><span><strong className="block text-sm">{title}</strong><small className="text-xs text-slate-500">{description}</small></span></span><ChevronRight size={18} className="text-slate-400" /></button>;
export default MobileMenuRedesigned;
