import React, { useState } from 'react';
import { Bell, ChevronLeft, ChevronRight, Heart, ShieldCheck, Smartphone, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

/* eslint-disable no-unused-vars */

const steps = [
    { eyebrow: 'Bem-vindo ao Duoo', title: 'A vida financeira de vocês, em sintonia.', description: 'O Duoo ajuda o casal a enxergar gastos, cartões, metas e decisões em uma única visão.', icon: Heart, color: 'bg-emerald-500' },
    { eyebrow: 'Privacidade primeiro', title: 'Sem acesso à sua conta bancária.', description: 'O Duoo não usa Open Finance. No Android, as transações podem ser identificadas pelas notificações que o banco envia.', icon: ShieldCheck, color: 'bg-blue-500' },
    { eyebrow: 'Ative a captura', title: 'Deixe o Duoo organizar seus avisos.', description: 'Para registrar compras, Pix e transferências automaticamente, permita o acesso às notificações no aplicativo nativo do Android.', icon: Bell, color: 'bg-amber-500' },
    { eyebrow: 'Construam juntos', title: 'Convide seu parceiro quando quiser.', description: 'Vocês podem começar sozinhos e conectar a conta do casal depois, sem perder o que já foi organizado.', icon: Users, color: 'bg-violet-500' }
];
const Brand = () => <div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700"><svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><circle cx="9" cy="12" r="6" /><circle cx="15" cy="12" r="6" /></svg></span><span className="text-xl font-semibold tracking-tight">duoo</span></div>;
const Illustration = ({ current, Icon }) => <><div className="relative flex h-36 w-full items-center justify-center overflow-hidden rounded-[32px] bg-emerald-50 dark:bg-emerald-950/30 sm:h-44 lg:hidden"><div className={`relative z-10 flex h-20 w-20 items-center justify-center rounded-[24px] text-white shadow-xl sm:h-24 sm:w-24 sm:rounded-[28px] ${current.color}`}><Icon size={38} strokeWidth={1.7} className="sm:hidden" /><Icon size={48} strokeWidth={1.7} className="hidden sm:block" /></div><span className="absolute left-[22%] top-7 h-3 w-3 rounded-full bg-emerald-300" /><span className="absolute bottom-7 right-[24%] h-5 w-5 rounded-full bg-blue-300" /><span className="absolute right-[27%] top-6 h-2 w-2 rounded-full bg-amber-300" /></div><div className="relative mx-auto hidden aspect-square max-w-sm items-center justify-center overflow-hidden rounded-[40px] bg-emerald-50 dark:bg-emerald-950/30 lg:flex" style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, rgba(10, 143, 99, 0.16) 1.5px, transparent 1.5px)', backgroundSize: '28px 28px' }}><div className={`relative z-10 flex h-28 w-28 items-center justify-center rounded-[32px] text-white shadow-2xl ${current.color}`}><Icon size={52} strokeWidth={1.7} /></div><span className="absolute left-12 top-14 h-3 w-3 rounded-full bg-emerald-300" /><span className="absolute bottom-20 right-16 h-5 w-5 rounded-full bg-blue-300" /><span className="absolute right-12 top-24 h-2 w-2 rounded-full bg-amber-300" /></div></>;
const Onboarding = () => {
    const navigate = useNavigate(); const { user } = useAuth(); const [step, setStep] = useState(0); const current = steps[step]; const Icon = current.icon;
    const finish = () => { localStorage.setItem('duoo:onboarding-complete', 'true'); navigate('/dashboard', { replace: true }); };
    const next = () => step === steps.length - 1 ? finish() : setStep((value) => value + 1);
    return <main className="min-h-screen bg-[#f7f8f5] px-4 py-5 text-slate-950 dark:bg-slate-950 dark:text-white sm:px-8 sm:py-6"><div className="mx-auto flex min-h-[calc(100vh-2.5rem)] max-w-5xl flex-col"><header className="flex items-center justify-between"><Brand /><button onClick={finish} className="rounded-xl px-2 py-2 text-sm font-medium text-slate-500 hover:bg-slate-100 hover:text-emerald-600 dark:hover:bg-slate-900">Pular</button></header><div className="flex flex-1 items-center justify-center py-8 sm:py-12"><div className="grid w-full items-center gap-8 lg:grid-cols-[.8fr_1.2fr] lg:gap-12"><Illustration current={current} Icon={Icon} /><section className="mx-auto w-full max-w-lg"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-emerald-600 sm:text-xs sm:tracking-[0.18em]">{current.eyebrow}</p><h1 className="mt-3 max-w-md text-3xl font-semibold leading-[1.12] tracking-tight sm:mt-4 sm:text-5xl">{current.title}</h1><p className="mt-4 max-w-md text-[15px] leading-relaxed text-slate-500 sm:mt-5 sm:text-base dark:text-slate-400">{current.description}</p>{step === 2 && <div className="mt-6 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-relaxed text-amber-800 dark:border-amber-900/40 dark:bg-amber-950/20 dark:text-amber-200"><Smartphone size={19} className="mt-0.5 shrink-0" /><span>Abra o app nativo no Android, permita o acesso às notificações e mantenha a captura ativa.</span></div>}{step === 3 && <div className="mt-6 flex items-center gap-3 rounded-2xl bg-slate-100 p-4 text-sm text-slate-600 dark:bg-slate-900 dark:text-slate-300"><Users size={19} className="shrink-0 text-violet-500" /> O convite pode ser feito em Menu → Conta do casal.</div>}<div className="mt-8 flex items-center gap-2 sm:mt-10">{steps.map((item, index) => <span key={item.eyebrow} className={`h-2 rounded-full transition-all ${index === step ? 'w-8 bg-emerald-500' : 'w-2 bg-slate-200 dark:bg-slate-700'}`} />)}</div><div className="mt-7 flex items-center justify-between gap-3 sm:mt-8"><button onClick={() => setStep((value) => Math.max(0, value - 1))} disabled={step === 0} className="inline-flex min-h-12 items-center gap-1 rounded-2xl px-3 text-sm font-medium text-slate-500 transition hover:bg-slate-100 disabled:invisible dark:hover:bg-slate-900 sm:gap-2 sm:px-4"><ChevronLeft size={17} /> Voltar</button><button onClick={next} className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-4 text-sm font-semibold text-white shadow-lg shadow-emerald-600/20 transition hover:bg-emerald-700 sm:flex-none sm:px-5">{step === steps.length - 1 ? 'Começar no Duoo' : 'Continuar'}{step < steps.length - 1 && <ChevronRight size={17} />}</button></div><p className="mt-5 text-center text-xs text-slate-400 sm:text-left">Olá, {user?.name?.split(' ')[0] || 'bem-vindo'}.</p></section></div></div></div></main>;
};
export default Onboarding;
