import React, { useEffect, useMemo, useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { Landmark, MoreHorizontal, Pencil, Plus, Trash2, Wallet as WalletIcon } from 'lucide-react';
import Card from '../components/ui/Card';
import Modal from '../components/ui/Modal';
import ConfirmModal from '../components/ui/ConfirmModal';
import Toast from '../components/ui/Toast';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import PageSkeleton from '../components/ui/PageSkeleton';
import { formatCurrencyInput, formatCurrencyValue, parseCurrencyInput } from '../utils/currency';

const currency = (value) => `R$ ${(Number(value) || 0).toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const inputClass = 'mt-2 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10 dark:border-slate-700 dark:bg-slate-800 dark:text-white';
const providers = { nubank: ['Nubank', 'bg-[#820AD1]'], inter: ['Banco Inter', 'bg-[#ff7a00]'], itau: ['Itaú', 'bg-[#ec7000]'], bradesco: ['Bradesco', 'bg-[#cc092f]'], xp: ['XP', 'bg-slate-950'], other: ['Outra instituição', 'bg-slate-700'] };

const WalletsRedesigned = () => {
    const { viewMode } = useOutletContext() || {};
    const { user, partner } = useAuth();
    const [wallets, setWallets] = useState([]); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(false); const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null); const [toast, setToast] = useState(null);
    const [form, setForm] = useState({ name: '', type: 'digital', provider: 'nubank', balance: '' });
    const load = async () => { setLoading(true); try { const { data } = await api.get('/wallets'); setWallets(data); } catch (error) { console.error(error); } finally { setLoading(false); } };
    useEffect(() => { load(); }, [viewMode]);
    const visibleWallets = wallets.filter((wallet) => viewMode === 'joint' || (viewMode === 'user1' && wallet.User?.id === user?.id) || (viewMode === 'user2' && wallet.User?.id === partner?.id));
    const total = useMemo(() => visibleWallets.reduce((sum, wallet) => sum + Number(wallet.balance || 0), 0), [visibleWallets]);
    const owner = (wallet) => wallet.User?.id === user?.id ? user?.name || 'Você' : wallet.User?.id === partner?.id ? partner?.name || 'Pessoa 2' : 'Conta';
    const open = (wallet = null) => { setEditing(wallet); setForm(wallet ? { name: wallet.name, type: wallet.type, provider: wallet.provider || 'nubank', balance: formatCurrencyValue(wallet.balance) } : { name: '', type: 'digital', provider: 'nubank', balance: '' }); setModal(true); };
    const save = async (event) => { event.preventDefault(); try { const payload = { ...form, balance: parseCurrencyInput(form.balance), provider: form.type === 'digital' ? form.provider : null }; if (editing) await api.put(`/wallets/${editing.id}`, payload); else await api.post('/wallets', payload); setModal(false); await load(); setToast({ message: editing ? 'Carteira atualizada.' : 'Carteira adicionada.', type: 'success' }); } catch (error) { setToast({ message: error.response?.data?.error || 'Erro ao salvar carteira.', type: 'error' }); } };
    const remove = async () => { try { await api.delete(`/wallets/${deleting}`); setDeleting(null); await load(); setToast({ message: 'Carteira excluída.', type: 'success' }); } catch (error) { setToast({ message: error.response?.data?.error || 'Erro ao excluir carteira.', type: 'error' }); } };
    if (loading) return <PageSkeleton />;
    return <div className="space-y-6 pb-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-sm font-semibold text-emerald-600">Contas do casal</p><h1 className="text-2xl font-semibold tracking-tight text-slate-950 dark:text-white">Carteiras</h1><p className="mt-1 text-sm text-slate-500">Organizem saldos, bancos e dinheiro disponível em um só lugar.</p></div><button onClick={() => open()} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-emerald-500 px-4 py-3 text-sm font-semibold text-white transition hover:bg-emerald-600"><Plus size={17} /> Adicionar carteira</button></header>
        <Card className="relative overflow-hidden bg-slate-950 p-6 text-white sm:p-8"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-emerald-500/20 blur-3xl" /><div className="relative"><div className="flex items-center gap-2 text-sm text-slate-300"><WalletIcon size={17} className="text-emerald-400" /> Saldo total visível</div><p className="mt-3 text-3xl font-semibold tracking-tight">{currency(total)}</p><p className="mt-2 text-sm text-slate-400">{visibleWallets.length} {visibleWallets.length === 1 ? 'carteira cadastrada' : 'carteiras cadastradas'}</p></div></Card>
        {visibleWallets.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visibleWallets.map((wallet) => { const provider = providers[wallet.provider] || providers.other; return <Card key={wallet.id} className="group relative overflow-hidden p-5 transition hover:-translate-y-0.5"><div className={`absolute right-0 top-0 h-24 w-24 translate-x-8 -translate-y-8 rounded-full opacity-10 ${provider[1]}`} /><div className="relative flex items-start justify-between"><div className={`flex h-11 w-11 items-center justify-center rounded-2xl text-white ${wallet.type === 'digital' ? provider[1] : 'bg-emerald-500'}`}>{wallet.type === 'digital' ? <Landmark size={20} /> : <WalletIcon size={20} />}</div><div className="flex gap-1 opacity-0 transition group-hover:opacity-100"><button onClick={() => open(wallet)} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100 hover:text-blue-600 dark:hover:bg-slate-800"><Pencil size={15} /></button><button onClick={() => setDeleting(wallet.id)} className="rounded-xl p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-slate-800"><Trash2 size={15} /></button></div></div><div className="relative mt-7"><p className="truncate font-semibold text-slate-950 dark:text-white">{wallet.name}</p><p className="mt-1 text-xs text-slate-500">{wallet.type === 'digital' ? provider[0] : 'Carteira física'} · {owner(wallet)}</p><p className="mt-4 text-2xl font-semibold tracking-tight text-slate-950 dark:text-white">{currency(wallet.balance)}</p></div></Card>; })}<button onClick={() => open()} className="flex min-h-[184px] flex-col items-center justify-center rounded-[20px] border border-dashed border-slate-300 text-sm font-medium text-slate-500 transition hover:border-emerald-400 hover:text-emerald-600 dark:border-slate-700"><Plus size={22} className="mb-2" />Adicionar outra</button></div> : <Card className="py-16 text-center"><WalletIcon className="mx-auto mb-3 text-slate-300" size={34} /><h2 className="font-semibold text-slate-900 dark:text-white">Nenhuma carteira por aqui</h2><p className="mt-1 text-sm text-slate-500">Cadastre sua primeira conta para acompanhar o saldo do casal.</p></Card>}
        <Modal isOpen={modal} onClose={() => setModal(false)} title={editing ? 'Editar carteira' : 'Nova carteira'}><form onSubmit={save} className="space-y-4"><label className="block text-sm font-medium">Nome da carteira<input required className={inputClass} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Ex.: Conta principal" /></label><div><span className="text-sm font-medium">Tipo</span><div className="mt-2 grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-1 dark:bg-slate-800"><button type="button" onClick={() => setForm({ ...form, type: 'digital' })} className={`rounded-xl py-2 text-sm font-medium ${form.type === 'digital' ? 'bg-white text-emerald-600 shadow-sm dark:bg-slate-700' : 'text-slate-500'}`}>Banco digital</button><button type="button" onClick={() => setForm({ ...form, type: 'physical' })} className={`rounded-xl py-2 text-sm font-medium ${form.type === 'physical' ? 'bg-white text-emerald-600 shadow-sm dark:bg-slate-700' : 'text-slate-500'}`}>Dinheiro físico</button></div></div>{form.type === 'digital' && <label className="block text-sm font-medium">Instituição<select className={inputClass} value={form.provider} onChange={(event) => setForm({ ...form, provider: event.target.value })}>{Object.entries(providers).map(([key, [label]]) => <option key={key} value={key}>{label}</option>)}</select></label>}<label className="block text-sm font-medium">{editing ? 'Saldo atual' : 'Saldo inicial'}<input required inputMode="decimal" className={inputClass} value={form.balance} onChange={(event) => setForm({ ...form, balance: formatCurrencyInput(event.target.value) })} placeholder="0,00" /></label><button className="w-full rounded-2xl bg-emerald-500 py-3 font-semibold text-white hover:bg-emerald-600">{editing ? 'Salvar alterações' : 'Criar carteira'}</button></form></Modal><ConfirmModal isOpen={!!deleting} onClose={() => setDeleting(null)} onConfirm={remove} title="Excluir carteira" message="Tem certeza que deseja excluir esta carteira?" type="danger" confirmText="Excluir" cancelText="Cancelar" />{toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}</div>;
};
export default WalletsRedesigned;
